# Generated by Django 4.1 on 2022-08-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('bottles_ordered', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Bottle',
        ),
    ]
